### ISSUE TITLE
Usage with Tag Manager

### ISSUE THREAD

**Issue by SiriusBits** [wistia/fresh-url#12]
There seems to be an issue running this with tag manager.

Pardot seems to function just fine.

**Comment by bschwartz** [comment]
Hey @SiriusBits, thanks for using FreshURL. We've got it running via GTM here: https://wistia.com/blog/ and it seems to be working just fine. Mind sending me a URL that isn't getting properly cleaned so I can take a look?

**Comment by bschwartz** [comment]
Hey @SiriusBits, going to close this for now. Let me know if you have some more info on it. Happy to re-open.
