### ISSUE TITLE
Issue with Twitter Ads

### ISSUE THREAD

**Issue by bsmye** [wistia/fresh-url#7]
Hi,

This is a bit of a random one, but basically there seems to be an issue with Fresh URL not waiting for a couple of analytics scripts to load (namely HubSpot). However, this is only occurring with Twitter ads links - it's not proving an issue anywhere else. So, in HubSpot, new leads coming from Twitter ads are being marked as direct traffic rather than Twitter.

I can't work out why this could be - any ideas?

Happy to clarify further if need be.

Thanks.

**Comment by bschwartz** [comment]
Hey B,

Do you have one of these links handy? If I can see it in action, I can probably fix it.
Thanks for reporting!

Brendan

**Comment by bsmye** [comment]
Hi Brenda,

Here you go:

https://t.co/WwSfmOSNJc

Thanks,
Ben.

**Comment by bsmye** [comment]
By the way, in case it makes any difference, I'm using the Eager.io integration for Fresh URL rather than the direct integration.

Thanks.

**Comment by bschwartz** [comment]
Hey Ben,

Thanks for the info. Looks like HubSpot changed the way their analytics JavaScript is embedded on the page. I just pushed a new version that I believe will fix this. I've also emailed @zackbloom from Eager about getting FreshURL updated on their side. As soon as that's done it should work for you.

Thanks again for bringing this up!

Brendan

**Comment by bsmye** [comment]
Brilliant, thank you very much Brendan!

Ben.

**Comment by zackbloom** [comment]
@bsmye Hi! Thanks for using Eager.  We've added the version of Fresh URL with this fix (0.1.4).  If you visit the edit page for your install you can update to the new version.  Please don't hesitate to shoot us a note at help@eager.io if you run into any trouble.

**Comment by bschwartz** [comment]
Thanks for doing that so quickly @zackbloom!

**Comment by bsmye** [comment]
Thanks again @bschwartz and @zackbloom for the quick work, I've reinstalled it so hopefully we're all good now!

Ben.
